## Reading the Data

In [ ]:
## Reading a json file
import pandas as pd
from io import StringIO
Data = '{"Name": "Raheel", "email": "example@gmail.com", "Status": [{"title1":"Student", "title2":"Data Analyst"}]}'
df=pd.read_json(StringIO(Data))
df

     Name              email                                           Status
0  Raheel  example@gmail.com  {'title1': 'Student', 'title2': 'Data Analyst'}

In [ ]:
## Converting back to json
df.to_json() ## brings index as a key in each sub key:value pair

'{"Name":{"0":"Raheel"},"email":{"0":"example@gmail.com"},"Status":{"0":{"title1":"Student","title2":"Data Analyst"}}}'

In [ ]:
df.to_json(orient='index') ## Only brings the index in the main key

'{"0":{"Name":"Raheel","email":"example@gmail.com","Status":{"title1":"Student","title2":"Data Analyst"}}}'

In [30]:
df.to_json(orient='records') ## removes the from key:value pair at all

'[{"Name":"Raheel","email":"example@gmail.com","Status":{"title1":"Student","title2":"Data Analyst"}}]'

In [ ]:
## Reading a csv file
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [ ]:
## Converting back to csv
df.to_csv('wine.csv') ## Automatically saved

In [ ]:
## Installing the necessary dependencies
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Downloading lxml-6.0.0-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 328.9 kB/s eta 0:00:11
   ------- -------------------------------- 0.8/4.0 MB 559.5 kB/s eta 0:00:06
   ---------- ----------------------------- 1.0/4.0 MB 645.7 kB/s eta 0:00:05
   ---------- ----------------------------- 1.0/4.0 MB 645.7 kB/s eta 0:00:05
   ------------- -------------------------- 1.3/4.0 MB 639.4 kB/s eta 0:00:05
   ------------- -------------------------- 1.3/4.0 MB 639.4 kB/s eta 0:00:05
   ------------------ --------------------- 1.8/4.0 MB 729.5 kB/s eta 0:00:03
   ------------------ --------------------- 1.8/4.0 MB 729.5 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 803.8 kB/s eta 0:00:03
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 857.9 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 314.2 kB/s eta 0:00:04
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 181.5 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 145.6 kB/s eta 0:00:05
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 119.2 kB/s eta 0:00:03
   ---------------------------------------  3.9/4.0 MB 114.5 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 116.5 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\internship_2025\day_1\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib

   ---------------------------------------- 0/2 [webencodings]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\internship_2025\day_1\venv\lib\site-packages (from beautifulsoup4) (4.14.0)
Downloading beautifulsoup4-4.13.4-py3-none-any.whl (187 kB)
Downloading soupsieve-2.7-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4

   ---------------------------------------- 0/2 [soupsieve]
   ---------------------------------------- 0/2 [soupsieve]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.13.4 soupsieve-2.7
Note: you may need to restart the kernel to use updated packages.

In [49]:
## Reading file through html 
url=("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")
df=pd.read_html(url) ## read_html works on tables only
df

[                               Bank Name           City         State   Cert  \
 0           The Santa Anna National Bank     Santa Anna         Texas   5520
 1                   Pulaski Savings Bank        Chicago      Illinois  28611
 2     The First National Bank of Lindsay        Lindsay      Oklahoma   4134
 3  Republic First Bank dba Republic Bank   Philadelphia  Pennsylvania  27332
 4                          Citizens Bank       Sac City          Iowa   8758
 5               Heartland Tri-State Bank        Elkhart        Kansas  25851
 6                    First Republic Bank  San Francisco    California  59017
 7                         Signature Bank       New York      New York  57053
 8                    Silicon Valley Bank    Santa Clara    California  24735
 9                      Almena State Bank         Almena        Kansas  15426

                  Acquiring Institution      Closing Date  Fund  Sort ascending
 0            Coleman County State Bank     June 27, 2025                 10549
 1                      Millennium Bank  January 17, 2025                 10548
 2   First Bank & Trust Co., Duncan, OK  October 18, 2024                 10547
 3    Fulton Bank, National Association    April 26, 2024                 10546
 4            Iowa Trust & Savings Bank  November 3, 2023                 10545
 5               Dream First Bank, N.A.     July 28, 2023                 10544
 6            JPMorgan Chase Bank, N.A.       May 1, 2023                 10543
 7                  Flagstar Bank, N.A.    March 12, 2023                 10540
 8  First Citizens Bank & Trust Company    March 10, 2023                 10539
 9                          Equity Bank  October 23, 2020                 10538  ]

In [51]:
df[0]['Bank Name']

0             The Santa Anna National Bank
1                     Pulaski Savings Bank
2       The First National Bank of Lindsay
3    Republic First Bank dba Republic Bank
4                            Citizens Bank
5                 Heartland Tri-State Bank
6                      First Republic Bank
7                           Signature Bank
8                      Silicon Valley Bank
9                        Almena State Bank
Name: Bank Name, dtype: object

In [ ]:
url=("https://en.wikipedia.org/wiki/Mobile_country_code")
df=pd.read_html(url,match='Country')[0] ## [0] for getting plain table

In [65]:
df.head(5)

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

In [68]:
## Installing the dependencies for proper working with excel files
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [ ]:
## Reading a excel file
pd.read_excel('correlation.xlsx')
df.head(5)

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

## Pickle file
## Binary file
## Important in machine learning projects

In [ ]:
## Convrting to pickle file
df.to_pickle('df_excel')

In [74]:
## Reading a pickle file
df=pd.read_pickle('df_excel')
df.head(5)

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN